name: qc-tools
channels:
  - bioconda
  - conda-forge
  - defaults 
dependencies:
  - multiqc=1.14
  - pillow=10.1.0
  - click=8.1.3
  - markdown
  - markdown-include=0.8.1
  - weasyprint=52.2
  - watchdog=3.0.0 
  - pandas 



